name: CI
on:
  push:
    branches: [main]

jobs:
  main:
   name: Publish HTML
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Output to HTML
        uses: netwerk-digitaal-erfgoed/bikeshed-action@v1